### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by meghnathomas** [tylertrimble/viswaternet#109] opened 2023-02-27 15:14 UTC
Make sure we are testing for versions >= 3.7 not only 3.10!

**Comment by meghnathomas** [comment] 2023-03-01 04:11
This issue will address comments from #111:

> Installation:
```
pip install viswaternet failed with python 3.11.0
ERROR: No matching distribution found for numpy==1.21.4
```
since you list as working with python 3.8+, it should work for 3.11.0. Let me know if you’re able to reproduce this, if not I can give a better trace
python 3.10.9 `python -m unittest` throws a lot of warnings
`MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead. cmap = mpl.cm.get_cmap(cmap)`

**Comment by tylertrimble** [comment] 2023-03-05 05:01
The numpy version issue is caused by WNTR. For some reason WNTR is requiring that 1.21.4 be installed, and that version of numpy does not work for python 3.11.

However, this issue should be fixed, as the people working on WNTR realized this and [made a commit last week](https://github.com/USEPA/WNTR/commit/fb20270e8ad0e6b2ad7d2047c8629c3fcf119752).

But when I manually installed WNTR on python 3.11 I get the error `No module named 'wntr.sim.aml._evaluator'` So even after bypassing the first issue, it appears that WNTR simply does not support Python 3.11 at the moment and we will have to wait for it to do so before our package can as well.

**Closed by tylertrimble** 2023-03-05 05:01 UTC
Labels: JOSS
